import type { Template } from "@shared/types";

export const templates: Template[] = [
  {
    id: "kanban",
    name: "Kanban Board",
    thumbnail: "📋",
    strokes: [
      {
        id: "t1",
        userId: "system",
        tool: "line",
        points: [{ x: 200, y: 100 }, { x: 200, y: 500 }],
        color: "#666",
        width: 2,
        timestamp: Date.now(),
      },
      {
        id: "t2",
        userId: "system",
        tool: "line",
        points: [{ x: 500, y: 100 }, { x: 500, y: 500 }],
        color: "#666",
        width: 2,
        timestamp: Date.now(),
      },
      {
        id: "t3",
        userId: "system",
        tool: "line",
        points: [{ x: 50, y: 100 }, { x: 750, y: 100 }],
        color: "#666",
        width: 2,
        timestamp: Date.now(),
      },
    ],
    stickies: [
      {
        id: "s1",
        userId: "system",
        x: 60,
        y: 120,
        width: 130,
        height: 180,
        text: "To Do\n- Task 1\n- Task 2\n- Task 3",
        color: "yellow",
        timestamp: Date.now(),
      },
      {
        id: "s2",
        userId: "system",
        x: 260,
        y: 120,
        width: 130,
        height: 180,
        text: "In Progress\n- Working on...",
        color: "blue",
        timestamp: Date.now(),
      },
      {
        id: "s3",
        userId: "system",
        x: 460,
        y: 120,
        width: 130,
        height: 180,
        text: "Done\n- Completed!",
        color: "green",
        timestamp: Date.now(),
      },
    ],
  },
  {
    id: "mindmap",
    name: "Mind Map",
    thumbnail: "🧠",
    strokes: [],
    stickies: [
      {
        id: "m1",
        userId: "system",
        x: 320,
        y: 200,
        width: 120,
        height: 60,
        text: "Central Idea",
        color: "violet",
        timestamp: Date.now(),
      },
    ],
  },
  {
    id: "flowchart",
    name: "Flowchart",
    thumbnail: "🔀",
    strokes: [],
    stickies: [
      {
        id: "f1",
        userId: "system",
        x: 300,
        y: 50,
        width: 140,
        height: 50,
        text: "Start",
        color: "green",
        timestamp: Date.now(),
      },
      {
        id: "f2",
        userId: "system",
        x: 300,
        y: 150,
        width: 140,
        height: 80,
        text: "Process",
        color: "blue",
        timestamp: Date.now(),
      },
      {
        id: "f3",
        userId: "system",
        x: 300,
        y: 280,
        width: 140,
        height: 50,
        text: "End",
        color: "pink",
        timestamp: Date.now(),
      },
    ],
  },
  {
    id: "sprint",
    name: "Sprint Planning",
    thumbnail: "🏃",
    strokes: [],
    stickies: [
      {
        id: "sp1",
        userId: "system",
        x: 50,
        y: 80,
        width: 180,
        height: 200,
        text: "Sprint Goal\n- Define objective",
        color: "yellow",
        timestamp: Date.now(),
      },
      {
        id: "sp2",
        userId: "system",
        x: 300,
        y: 80,
        width: 180,
        height: 200,
        text: "Backlog\n- Story 1\n- Story 2",
        color: "purple",
        timestamp: Date.now(),
      },
      {
        id: "sp3",
        userId: "system",
        x: 550,
        y: 80,
        width: 180,
        height: 200,
        text: "Tasks\n- Design\n- Code\n- Test",
        color: "blue",
        timestamp: Date.now(),
      },
    ],
  },
  {
    id: "interview",
    name: "Interview Prep",
    thumbnail: "💼",
    strokes: [],
    stickies: [
      {
        id: "i1",
        userId: "system",
        x: 50,
        y: 50,
        width: 200,
        height: 150,
        text: "Candidate Notes\n- Experience\n- Skills",
        color: "green",
        timestamp: Date.now(),
      },
      {
        id: "i2",
        userId: "system",
        x: 320,
        y: 50,
        width: 200,
        height: 150,
        text: "Questions\n- Technical\n- Behavioral",
        color: "yellow",
        timestamp: Date.now(),
      },
      {
        id: "i3",
        userId: "system",
        x: 590,
        y: 50,
        width: 200,
        height: 150,
        text: "Feedback\n- Pros\n- Cons",
        color: "pink",
        timestamp: Date.now(),
      },
    ],
  },
  {
    id: "systemdesign",
    name: "System Design",
    thumbnail: "⚙️",
    strokes: [],
    stickies: [
      {
        id: "sd1",
        userId: "system",
        x: 50,
        y: 50,
        width: 220,
        height: 120,
        text: "Requirements\n- Functional\n- Non-Functional",
        color: "violet",
        timestamp: Date.now(),
      },
      {
        id: "sd2",
        userId: "system",
        x: 350,
        y: 50,
        width: 220,
        height: 120,
        text: "Components\n- API\n- DB\n- Cache",
        color: "blue",
        timestamp: Date.now(),
      },
      {
        id: "sd3",
        userId: "system",
        x: 650,
        y: 50,
        width: 220,
        height: 120,
        text: "Trade-offs\n- Consistency\n- Availability",
        color: "green",
        timestamp: Date.now(),
      },
    ],
  },
];

export function loadTemplate(templateId: string): Template | undefined {
  return templates.find((t) => t.id === templateId);
}
